### ISSUE TITLE
Collecting list of successful Open Source communities

### ISSUE THREAD

**Issue by bgruening** [aidanbudd/bosc2015#13]
The idea is to have a list of communities and write a short paragraph about them.
Moreover, we can contact each of them to get opinions and solve: https://github.com/aidanbudd/bosc2015/issues/9
- [Galaxy](http://galaxyproject.org/)
  - [GalaxyP](https://github.com/galaxyproteomics/tools-galaxyp)
  - [IUC](https://github.com/galaxyproject/tools-iuc)
- [BioJS](http://biojs.net/) ([community paper](http://www.ncbi.nlm.nih.gov/pubmed/26153621))
- [BioConductor](http://bioconductor.org/)
- [BioPython](http://biopython.org)
- [BioPerl](http://www.bioperl.org)
- [GMOD](http://www.gmod.org)
- Education
  - [data carpentry](http://datacarpentry.org/)
  - [software carpentry](http://software-carpentry.org/)
  - [Goblet](http://www.mygoblet.org/)

Please feel free to add more.

**Comment by aidanbudd** [comment]
By default, I'd limit it to code-producing communities i.e. not including e.g. educational ones listed above. I guess that's because I'm interested, this time, in being more focused than a previous more general look at bioinformatics communities http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003972 , looking to provide more specific advice/experience for people working on writing code together.

But that's just my preference.

**Comment by aidanbudd** [comment]
I've added the list above to a file in the repo, might make it easier to collect/edit a list of the communities in listOfOSBCs.md - Bjoern, if you rather collect it here in this issue, please go ahead and remove the file

**Comment by bgruening** [comment]
@aidanbudd this is ok with me. Please feel free to remove the educational once.

**Comment by aidanbudd** [comment]
Alrighty - just done that.

**Comment by ghost** [comment]
Just to be clear (for myself & other readers) - the list can include either Bioinformatics or Cheminformatics open-source software, and/or open-source workflow management systems (e.g. Galaxy, Taverna). 

Can we use open-source projects like https://ropensci.org/blog/ as examples? :)

**Comment by bgruening** [comment]
I would say yes! But I would also add (and now it gets tricky) that these projects also need to be successful in creating a community.
Imho, there is a difference in great open-source projects and great community driven open-source projects.

**Comment by sjackman** [comment]
- [Homebrew](http://brew.sh) 4,982 contributors as of 2015-08-09
- [Homebrew-science](http://brew.sh/homebrew-science) 378 contributors

**Comment by aidanbudd** [comment]
@sjackman, happy to add those to the list for you and/but if you were up for it, would be great if you could propose it via fetch/pull requests - I hope that by trying to do most of the collaborative writing that way, we're less likely to miss out including people's contributions. But if you prefer me to add it myself, just let me know, and I'll do it.

**Comment by bgruening** [comment]
Awesome! Looking forward to @sjackman thoughts about building communities.
@aidanbudd If we add this we should also think about the other deployment platforms, [DebianMed](https://wiki.debian.org/DebianMed) for example.

**Comment by sjackman** [comment]
Done. https://github.com/aidanbudd/bosc2015/pull/25

**Comment by svaksha** [comment]
Hi,
I maintain a list of packages for the [Julia](https://github.com/svaksha/Julia.jl/blob/master/Biology.md) and [Python](https://github.com/svaksha/pythonidae/blob/master/Biology.md) programming languages. Can I add them to the list, for example: BioJulia/JuliaBio, etc.. and submit a PR? Thanks!

**Comment by aidanbudd** [comment]
Hi @svaksha - you need to follow me on Twitter for me to be able to send you a DM to share email addresses - I've followed you.

**Comment by svaksha** [comment]
Sent

**Comment by aidanbudd** [comment]
Closing this issue, to consolidate discussion of which communities to include/reach out to for the manuscript into one issue i.e. #38
