### ISSUE TITLE
Which kind of communities to include in discussion/examples?

### ISSUE THREAD

**Issue by aidanbudd** [aidanbudd/bosc2015#18]
In #17 @bgruening suggested spinning out some of his questions in there to separate issues - here I'm doing that with something several of us have discussed.

My first call would be to include things that are definitely "Open Source". Although I don't have a definition of that - someone with more knowledge of this could perhaps propose/suggest one/some generally used ones?

**Comment by aidanbudd** [comment]
Then, concerning 'domain', I'm also keen that the opinions we gather are as useful as possible for people building/contributing to Open Source bioinformatics communities they are part of (given that my experience is focused on bioinformatics). If the lessons and features of these are going to be almost entirely the same for any Open Source community, then I'd say let's consider including any of those, and adapting the provisional title to remove the 'bioinformatics".

But I'm not precious about any of this - would like to hear what you think, and decide together what we think a good scope to focus on would be.

**Comment by bgruening** [comment]
I would start with the [OSI](http://opensource.org/osd) definition and with the list of [approved Open Source](http://opensource.org/licenses/alphabetical) licenses.
In addition I would like to discuss issues with restricted licensing for special user groups. Like academic only ... or some kind of.

**Comment by aidanbudd** [comment]
@bgruening how about you create a new file in the repo for the "introduction", and start putting these links and comments and ideas in there?

**Comment by bgruening** [comment]
I'm still not sure how the repo should like in the end :)
You mean an `introduction.md` file?

**Comment by aidanbudd** [comment]
Yes, that's what I meant.

You reckon it's better to keep the number of files small? 

I'm novice doing this kinda thing, if you reckon it's better to collect that stuff later, or in a different way, I'm more than good with that.

**Comment by bgruening** [comment]
I think this is novice for all of us :).
I would like to keep it as issue and at some point we can sit together and write a first draft, collection all issues.

**Comment by aidanbudd** [comment]
Good - happy to do it that way.

**Comment by ghost** [comment]
Hi @bgruening could you please describe a bit more of your point about "issues with restricted licensing and special user groups." I don't think I really understand it :( Do you mean, for example, PyMOL? that only licensed users can download -_-  lol or any closed-source license for software project? Also, why is it important to consider this point in terms of open-source software/community? Just wondering :)

**Comment by bgruening** [comment]
@NFatima I don't consider projects open-source if you are not allowed to distribute software or if any sub-community is left out. PyMOL is ok imho, you can get the source afaik and debian can redistribute it.

**Comment by aidanbudd** [comment]
Closing this issue, to consolidate discussion of which communities to include/reach out to for the manuscript into one issue i.e. #38
