### ISSUE TITLE
Adding examples/experience/anecdotes from real communities to our collected features.

### ISSUE THREAD

**Issue by aidanbudd** [aidanbudd/bosc2015#21]
Based on the BioJS eLife article, and the content collected during the Open Space session at BOSC2015, I've started adding more flesh to the features document.

I'm trying that, so we can get a feeling of how is a good way to add/introduce examples/anecdotes from many different example OSBCs. Hopefully, when others see how we've added such content, it'll be clearer to them how to do the same.

As I don't actually contribute any code, or use any of these myself at the moment (as a project manager I hardly ever write any code any more), would be great if some of you could have a go at adding this kind of thing based on your much more current experiences of this kind of thing!

I may need, once several of us have added something, discuss how to most usefully do this, but we won't know that until we start looking at what different people put in.

**Comment by malvikasharan** [comment]
Thanks a lot Aidan. IMO the discussion chain like this can help us think clearly about what to write/add. 

Just a heads up, Many people (living in Europe) seem to be on holidays right now, so hopefully we can expect higher contributions after August.

**Comment by aidanbudd** [comment]
Thanks for that, Malvika - aye, you're right about the holidays - it's funny, at the moment, as you say, many are away, but the flip side of that is that I (now I'm back from my own holidays!) have actually got some time free to devote to pushing this along!! :)

**Comment by aidanbudd** [comment]
Closing this issue, to consolidate discussion of which communities to include/reach out to for the manuscript into one issue i.e. #38
