### ISSUE TITLE
Redundant points

### ISSUE THREAD

**Issue by malvikasharan** [aidanbudd/bosc2015#6]
Could we comment on the redundant points? for example:
Following points more or less indicate to same feature "Open transparent effective efficient respectful communication"
Extensive access to and communication with users
Quick responses to bug fixes/feature requests
Easy to contribute to

**Comment by aidanbudd** [comment]
Thanks for that, Malvkia.

Don't know how best to deal with this issue.

You're right, the bottom three points are all aspects of the first.

At the same time, I think it's useful to highlight those particular aspects of the general point, as being common features of great communities.

Perhaps include all the points, and at the top of the 'subfeatures' put the text 'This is a specific aspect of feature "Open transparent effective efficient respectful communication", but is included as it's a very specific important case of that, one that if it's not there, can have major negative impact on the quality of the community" (or something much more elegantly worded than that"...?

So it becomes clearer, that the set of features we're looking to list may include 'subfeatures' (i.e. there's some kind of branching/heirachy here). Justification for including a particular subfeature as an important enough aspect of the main feature, to be included on its own, is that it's a particular subfeature that has been observed as a common one that is not followed and causes problems/non-greatness for the community...?

**Comment by malvikasharan** [comment]
Thanks for addressing this. The idea of branching/heirarchy can guide the texts to be included for each main feature.

Just so its clear, do you suggest that at the end of the feature collection we can decide 'subfeatures' of a main feature or should we address/explain each point separately during text writing?

**Comment by aidanbudd** [comment]
I encourage you to do it the way that feels most useful/appropriate to you - we can change this as we go along, if we feel it needs alternative approaches.

**Comment by bgruening** [comment]
I'm will close this for now.
