### ISSUE TITLE
Attracting more contributors

### ISSUE THREAD

**Issue by aidanbudd** [aidanbudd/bosc2015#9]
Hi Bjoern, Hi Malvika,

Thanks so much for contributing to this!

Would be great to have some more people giving their insights.

I guess the ways to get more are:
- wait (someone mailed me to say they'll do something next week)
- ask people we know (particularly those at the sessions in BOSC) to contribute
- ask/contact some of the 'obvious' communities directly, asking for their input (I don't know, bioperl, biojs, etc.)

If we make a list of projects here, would you be up for dividing them up to contact them?

frustratingly, my laptop has just died, so I'll be slower than planned the next days :-/

**Comment by malvikasharan** [comment]
I have already reminded Konrad about it. It might be helpful to send an email to everyone from the BoF. If not to everyone, at least people who knew more people from the BoF.

**Comment by aidanbudd** [comment]
Just posted a link to this repo at BioStars https://www.biostars.org/p/153770/

**Comment by bgruening** [comment]
@peterjc any chance that @aidanbudd can send a mail to all BOSC participants?
And Peter, please feel free to add you comments as BioPython maintainer (and more!) to this project!

**Comment by peterjc** [comment]
All the BOSC 2015 participants should have already had an email from Nomi on 21 July titled "BOSC 2015 followup" which included the forwarded email from @aidanbudd

Also OBF_BOSC has retweeted/tweeted about this too.

**Comment by aidanbudd** [comment]
Sorry to be late on this - yes, BOSC already helped a lot with this, thanks a lot for that @peterjc 

If you  (@peterjc) do have time and motivation to add any anecdotes/experience/comments in listOfFeaturesOfGreatOSBCs.md about how/why the features listed there have been important/illustrated in biopython, we're hoping to move now to collecting that kinda info, rather than collating the initial list of features.

**Comment by aidanbudd** [comment]
Closing this issue, to consolidate discussion of which communities to include/reach out to for the manuscript into one issue i.e. #38
